name: victim
filebeat.modules:
  - module: system
    syslog:
      enabled: false
    auth:
      enabled: true
      var.paths: ["/victim-logs/auth.log"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
